### ISSUE TITLE
FR: Add Full Calendar Standard Support

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-events#10]
Add ability to use the FullCalendar bundle to have an instant working calendar out of the box.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3nb2n)

**Comment by edalzell** [comment]
I don't understand what we'd provide here, can you give an example @adnankussair?

**Comment by adnankussair** [comment]
@edalzell Not necessary. Instead for simple we should build out using tailwind UI (calendar blocks). Need to port simple to tailwind first.
