### ISSUE TITLE
Recurring Events Collapse Inquiry

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-events#12]
My support request is regarding: CMS (Content Management System)
Domain which you need assistant with (if applicable): cypressclub.ca

Tell us what is going wrong: I have a question about your STATAMIC EVENTS addon.

I am listing events on a web page, and certain events are, like, month-long events (like. say, July is Half Price Pasta month... or something like that).

When I add the event as a recurring event (Daily, all day, every day in July), the site displays every day individually.

I know with multi-day events, you can collapse the listing with "collapse_multi_days". It's a bit of a pain to do a monthly event with Multi-Day because each day has to be entered individually.

Is it possible to collapse a recurring date, and just show the rule (like "All Day, Daily") or whatever? I don't want to list all 30 days, but I can't seem to collapse a recurring event... because it technically is ONE event that just lasts all month.

Let me know if this is possible and/or if this is the right place to ask questions about your addon. THank you!

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_40aq7)

**Comment by edalzell** [comment]
they should use multi-day events. If they want that feature (and gcal integration), they can open an FR.
