### ISSUE TITLE
Getting error: Modifier [events.is_start_of_week] not found 

### ISSUE THREAD

**Issue by austriker27** [transformstudios/statamic-events#13]
Hey all, 

This looks like a great package! I'm either doing something wrong or I found a bug. I'm getting an error when I try to drop in the [calendar](https://github.com/transformstudios/statamic-events/blob/main/calendar.html) example.

## Error
`Modifier [events.is_start_of_week] not found`

## Steps to reproduce:

1. Install package (I'm on `"transformstudios/events": "^2.2"`)
2.  Publish the tag: `php artisan vendor:publish --tag=events-config`
3. Create `events` collection and add your [event fieldset](https://github.com/transformstudios/statamic-events-v3/blob/main/resources/fieldsets/event.yaml)
4. Import the event fieldset into the events collection

### 

## My events collection blueprint:
```twig
title: Events
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          type: markdown
          display: Content
          localizable: true
      -
        import: event
      -
        handle: website
        field:
          display: Website
          type: link
          icon: link
          listable: hidden
      -
        handle: cover_image
        field:
          mode: grid
          container: assets
          folder: events
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Cover Image'
          type: assets
          icon: assets
          listable: hidden
      -
        handle: facebook_event
        field:
          display: 'Facebook Event'
          type: link
          icon: link
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: author
        field:
          type: users
          display: Author
          default: current
          localizable: true
          max_items: 1
      -
        handle: template
        field:
          type: template
          display: Template
          localizable: true

```

**Comment by edalzell** [comment]
@austriker27 docs are wrong, use the modifier without the events part, just is_start_of_week

**Comment by austriker27** [comment]
> @austriker27 docs are wrong, use the modifier without the events part, just is_start_of_week

Oh okay! Thanks!

**Comment by austriker27** [comment]
> @austriker27 docs are wrong, use the modifier without the events part, just is_start_of_week

Its working now after I drop the modifiers! 

Random follow up - do you happen to the CSS for the calendar example laying around somewhere? Or was it written in bootstrap? It would save me some time and I dont see it linked anywhere - id like to tailwind-ify it.

EDIT: Never mind, I did some sleuthing and found your [live](https://zaytuna.edu/events) example which has helped me a lot to get an idea of what it should be like... Here's my WIP 😀

![image](https://user-images.githubusercontent.com/14855925/133787572-cab71075-eff9-4ea0-972a-a27508f46d75.png)

**Comment by edalzell** [comment]
Fixed the docs, thanks @austriker27
