### ISSUE TITLE
Getting error when I use download link feature

### ISSUE THREAD

**Issue by austriker27** [transformstudios/statamic-events#14]
Hello again, 

I'm trying to use the download link feature but getting an error. I copied pasted from the docs but am using `start_date` because its the date on my events collection schema. 

## Error
```php
TypeError
Argument 4 passed to Spatie\CalendarLinks\Link::create() must be of the type bool, object given, 
```

## My HTML:
```
<a href="{{ events:download_link
  start_date="{{ get:start_date }}"
  type="google"
}}">Google</a>
```

## Example event:
```md
---
id: cc56741e-9ebf-4049-8a8e-c06bc5478eb2
blueprint: events
title: 'Bothell Maker''s Market'
author: 6bbb8ea9-e8f0-4906-9f24-af95d70f961c
all_day: false
multi_day: false
start_date: '2021-09-25'
start_time: '10:00'
end_time: '18:00'
days:
  -
    date: null
    start_time: null
    end_time: null
  -
    date: null
    start_time: null
    end_time: null
recurrence: '0'
updated_by: 6bbb8ea9-e8f0-4906-9f24-af95d70f961c
updated_at: 1631797998
website: 'https://www.bothellmakermarket.com/'
cover_image: events/BMM-Social-Media-Graphics-07.jpg
facebook_event: 'https://www.facebook.com/events/170350858560819'
---
Join us in Bothell on 9/25 with tons of other amazing small businesses and makers!
```

## Directions screenshot:
![image](https://user-images.githubusercontent.com/14855925/133854157-2f3d8c45-975f-49dc-9a9d-b1834a6f3653.png)
https://statamic.com/addons/transform/events/docs#fieldset

**Comment by edalzell** [comment]
Fixed in 2.2.2 @austriker27 give it a try.

**Comment by austriker27** [comment]
> Fixed in 2.2.2 @austriker27 give it a try.

Nice that's fixed that bug! 

In my testing, Google and Outlook are working pretty well. But for the Apple/ICS event, it downloads a file that's missing a title (`.ics`) which means its not readily recognized as a calendar event.

Also I have follow up questions now that the event download is working.

Follow up 2: Is it possible at this point to change that field populates the event file? Right now my event title is just " Bothell Maker's Market" but I would prefer to change that so I can do something like "Rainier Watch at Bothell Maker's Market". Is this an FR? 

Question 3: I added an address field on to my events - can the event download link use that for the event address? Or is that another FR? 

Thanks!

**Comment by edalzell** [comment]
> In my testing, Google and Outlook are working pretty well. But for the Apple/ICS event, it downloads a file that's missing a title (.ics) which means its not readily recognized as a calendar event.

New issue, please submit.

**Comment by edalzell** [comment]
> Follow up 2: Is it possible at this point to change that field populates the event file? Right now my event title is just " Bothell Maker's Market" but I would prefer to change that so I can do something like "Rainier Watch at Bothell Maker's Market". Is this an FR?

That's an FR, please submit

**Comment by edalzell** [comment]
> Question 3: I added an address field on to my events - can the event download link use that for the event address? Or is that another FR?

Yet another FR
