### ISSUE TITLE
Download calendar file: ICS filename missing

### ISSUE THREAD

**Issue by austriker27** [transformstudios/statamic-events#15]
In my testing with version 2.2.2, the calendar download link generates a file that is just `.ics` which is missing the filename - this prevents a computer from recognizing the file as a calendar file. 

Here's my sample file I generated (In a zip file)
[ics.zip](https://github.com/transformstudios/statamic-events-v3/files/7192927/ics.zip)

**Comment by edalzell** [comment]
Hey there @austriker27 is this still occurring for you? FYI Events is now at 3.3.3.

If it is still occurring, does that event entry have a `title`?

**Comment by edalzell** [comment]
@austriker27 this is returning a base64 `data:text/calendar` string. To set the name of the download, use the `download` attribute, like this:

```
<a download="event-{{ date format='Ymd' }}.ics" href="{{ events:download-link }}" title="Download .ics to add to your calendar">Add to calendar</a>`
```

I'll add that to the docs, thanks!

**Comment by austriker27** [comment]
> @austriker27 this is returning a base64 `data:text/calendar` string. To set the name of the download, use the `download` attribute, like this:
> 
> ```
> <a download="event-{{ date format='Ymd' }}.ics" href="{{ events:download-link }}" title="Download .ics to add to your calendar">Add to calendar</a>`
> ```
> 
> I'll add that to the docs, thanks!

Oh okay, thank you!
