### ISSUE TITLE
FR: Improve the Calendar Event File Download 

### ISSUE THREAD

**Issue by austriker27** [transformstudios/statamic-events#16]
It would be great to be able to edit the calendar event that's generated by the download feature and map it to our own fields. 

For example, my event's title is "Fall Market" but I'd prefer to add in my company name so its "Vandelay's Fall Market".

Also in addition to editing the event title I'd love to map to my own fields - for uses like setting an address on the calendar event.

**Comment by austriker27** [comment]
Maybe this is 2 FRs - I can split it (edit title, add custom fields) if desired

**Comment by edalzell** [comment]
What would this look like @austriker27 can you give an example of how you'd like to use it (Antlers example please)

**Comment by edalzell** [comment]
> For example, my event's title is "Fall Market" but I'd prefer to add in my company name so its "Vandelay's Fall Market".

Yes, please split into two, with examples of how you'd like to do each of them.
