### ISSUE TITLE
Week Start on Monday?

### ISSUE THREAD

**Issue by jeverington** [transformstudios/statamic-events#24]
How can i set the weeks returned to start on a Monday instead of a Sunday?

**Comment by edalzell** [comment]
What's your use case @jeverington ?

**Comment by hgrimelid** [comment]
In many parts of the world (for example most of Europe) the week starts on a Monday and ends on a Sunday. It would be great if this could be set in the config.

I've identified hard coded values for start/end of week in:
- `src/Tags/Events.php`
- `src/Http/Controllers/CalendarController.php`
- `src/Modifiers/IsEndOfWeek.php`
- `src/Modifiers/IsStartOfWeek.php`

**Comment by jeverington** [comment]
@edalzell I think @hgrimelid sums it up well!

**Comment by edalzell** [comment]
This may be a large breaking change, as the date generation code is a bit ugly.

In my upcoming refactor, this will not be an issue.

@jeverington @hgrimelid what issues does this cause for you?

**Comment by hgrimelid** [comment]
I think the calendar view is what's the main problem with today's version. That said, I've just started building the site which is supposed to use this addo, so there might be other issues that I've not yet stumbled upon.

**Comment by adnankussair** [comment]
Hey @hgrimelid! What's the timeline on this site build? I think the refactor is where I'd like us to spend the time vs. trying to make the current version work for "start on Monday."

**Comment by hgrimelid** [comment]
We've not yet decided whether we need the calendar view, so it's probably the best option that you prioritize according to your preferences.

**Comment by adnankussair** [comment]
Will do. Thanks @hgrimelid
