### ISSUE TITLE
Error When trying to create entry with events-fieldset

### ISSUE THREAD

**Issue by spetz83** [transformstudios/statamic-events#25]
Statamic Version: 3.2.38
Events Version: 3.3.3

I have a fresh Statamic install. I installed the events addon and published the config and fieldset.
I have a collection called Events. I added the published fieldset to the Events blueprint. 
When I attempt to create a new entry in the events collection, I get the following error:

![image](https://user-images.githubusercontent.com/291664/158615611-63a90aaf-ea7d-4105-90d8-7f1dc21c156a.png)

Removing the events fieldset from the events blueprint resolves the error.
I tried adding the events fieldset to another collection's blueprint and I receive the same error when trying to create entries. 

Any guidance would be appreciated

**Comment by edalzell** [comment]
Let's see the blueprint please

**Comment by edalzell** [comment]
It's this bug @spetz83 : https://github.com/statamic/cms/issues/4669, remove that data and it'll all work.
