### ISSUE TITLE
Multi Day Event & Wrong Date Appended

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-events#30]
- [x] Getting Wrong Date appended to end of URL:

<img width="544" alt="Screen Shot 2022-04-01 at 8 16 42 PM" src="https://user-images.githubusercontent.com/239259/161363859-6ad9fb68-ca65-4e77-80e5-304d349c5b60.png">

Has a url of `/events/1st-night-of-taraweeh?date=2022-03-15` note event is for 2022-04-01

- [x] Multi-Day Event Breaks Events 2 Block, possible multi-day bug:

<img width="1285" alt="Screen Shot 2022-04-01 at 8 06 15 PM" src="https://user-images.githubusercontent.com/239259/161363909-5b29d7ff-cb5d-49fe-822b-718a933766ce.png">

Upon publishing this multi-day event the block is displaying fine again:

<img width="984" alt="Screen Shot 2022-04-01 at 8 12 03 PM" src="https://user-images.githubusercontent.com/239259/161363941-6330ed26-a202-4f5c-a66f-b762f14116b8.png">

**Comment by edalzell** [comment]
Some recent parser changes broke `event_snippet` partial. 

And the `date` was wrong in the calendar, don't know why. Used `scope` to work around the issue, though it may be a bug in the Events addon.

@adnankussair should look at this next week to fix it properly.

**Comment by edalzell** [comment]
Closing in favour of https://github.com/transformstudios/statamic-events-v3/issues/29
