### ISSUE TITLE
Download link docs are wrong

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-events#36]
Alright got it working. I think the documentation is incorrect. That being said I also had my handle for 'events' as 'event'...🤷‍♂️

https://statamic.com/addons/transform/events/docs

```
<a
    download="event-{{ date format='Ymd' }}.ics"
    href="{{ events:download_link
    start_date="{{ get:date }}" {{# getting the date from the `date` query param #}}
    type="google"
}}">Google</a>
```

Thank you for the assistance.

_Originally posted by @davidatkinswwt in https://github.com/transformstudios/statamic-events/issues/35#issuecomment-1119859162_

**Comment by adnankussair** [comment]
@edalzell Looks like we never updated this in the docs.
