### ISSUE TITLE
FR: Add fieldtype or publish fieldset

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-events#4]
Would be way better if folks could simply add an `event` fieldtype to their data.

Do this as part of transformstudios/statamic-events#7

**Comment by edalzell** [comment]
Could also create a fieldset and publish that

**Comment by adnankussair** [comment]
@edalzell Okay to close?

**Comment by edalzell** [comment]
> @edalzell Okay to close?

Not yet, no.

**Comment by edalzell** [comment]
You publish the fieldset.
