### ISSUE TITLE
Generated/Downloadable Files are blank

### ISSUE THREAD

**Issue by davidatkinswwt** [transformstudios/statamic-events#40]
Back again...

I'm having issues with the generated/downloadable ICS files (along with all the others).

Rather than try to explain my issues I've setup this you can preview my issue on this Test Site.

- Fresh Events install
- Added Event Fieldset
- Added Event Fieldset to Events Blueprint
- Added Data

Downloaded ICS file is considered invalid.

Any help would be greatly appreciated. Thanks!

https://github.com/davidatkinswwt/testsite.git

Control Panel Credentials
Email: admin@testsite.com
Pass: password

<img width="328" alt="Screen Shot 2022-06-10 at 8 31 48 AM" src="https://user-images.githubusercontent.com/28378640/173076582-9d8e5ff5-8613-4b89-9e70-de13b89218bd.png">
<img width="396" alt="Screen Shot 2022-06-10 at 8 33 07 AM" src="https://user-images.githubusercontent.com/28378640/173076871-a32e280b-3cba-43b1-ac5a-f7d69ffd8ffc.png">

**Comment by adnankussair** [comment]
Hey @davidatkinswwt thanks for reporting. We'll take a looksie and report back.

**Comment by adnankussair** [comment]
Hey @davidatkinswwt. Sorry we haven't been able to get to this issue. We're hoping to take a look early next week.

**Comment by edalzell** [comment]
Thanks for the great bug report @davidatkinswwt, looking at this now.
