### ISSUE TITLE
Incorrect times for event download .ics

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-events#45]
Was there a fix to this? the code in the documentation does not work.  I've tried to tweak a bit but no luck.  I also did what Erin did and the event was actually able to be added to calendar (however times were incorrect).

_Originally posted by @ecksullivan8 in https://github.com/transformstudios/statamic-events/issues/35#issuecomment-1295850278_

**Comment by edalzell** [comment]
@ecksullivan8 do you have some examples of this so I can try to figure this out?

**Comment by edalzell** [comment]
I cannot reproduce this, the times come in properly.

If you can provide a repo that shows the issue, I will re-open.
