### ISSUE TITLE
Limit doesn't seem to be working for upcoming events

### ISSUE THREAD

**Issue by qbixx** [transformstudios/statamic-events#55]
We've added a new loop with the code below. We have setup a `limit` like provided in the documentation. However when we use this code, the limit isn't applied and all events are showing up. Do we perhaps use the wrong code?

`{{ events:upcoming collection="acties" limit="12" collapse_multi_days="true" }}`

**Comment by edalzell** [comment]
Does it work if you remove the `collapse_multi_days`?

**Comment by qbixx** [comment]
I just tried a few different settings. Will post the outcomes below:

`{{ events:upcoming collection="acties" limit="12" collapse_multi_days="true" }}`
Number of events shown: 82

`{{ events:upcoming collection="acties" limit="12" }}`
Number of events shown: 82

{{ events:upcoming collection="acties" limit="2" }}
Number of events shown: 21

When looking at the events that are showing, there is a loop of the same events (see screenshot):
![Screenshot 2023-02-27 at 14 45 26](https://user-images.githubusercontent.com/1932778/221579992-927a271d-2348-45f2-a363-0c1563b4c3cd.png)

**Comment by edalzell** [comment]
Thanks for this, I'll look at this this week.
