### ISSUE TITLE
Download to Calendar tag isn't working for me.

### ISSUE THREAD

**Issue by jeremyhakai** [transformstudios/statamic-events#61]
This is the tag I'm using:

```
<a
    download="event-{{ date format='Ymd' }}.ics"
    href="{{ events:download_link event="{ id }" date="{ get:date }" {{# getting the date from the `date` query param #}}
}}">Download to your calendar</a>
```

The generated link is:

https://bioactnet.ddev.site:8443/!/events/ics?collection=events&date=2023-08-01&event=5d3784be-813e-4b2f-9484-b9d118804143

It won't let me attach the .ics file, so I've renamed it .txt and attached it; it's just the webpage.
[event-20230801.txt](https://github.com/transformstudios/statamic-events/files/12224820/event-20230801.txt)

**Comment by edalzell** [comment]
@adnankussair we should look at this one

**Comment by adnankussair** [comment]
@jeremyhakai Thanks for reporting, we're on it.
@edalzell Might be related to the log error we got on ZF.

**Comment by edalzell** [comment]
> @edalzell Might be related to the log error we got on ZF.

Nope

**Comment by edalzell** [comment]
@jeremyhakai I can't reproduce, are there any errors in the log for this?

Does this event, `5d3784be-813e-4b2f-9484-b9d118804143` exist? If so, can I see the blueprint and the data?

**Comment by adnankussair** [comment]
@jeremyhakai We're closing this for now as we could not reproduce it. If you are still having issues here, feel free to reach out with the blueprint and data for the event that you can reproduce this error.
