### ISSUE TITLE
Incomplete paginate array

### ISSUE THREAD

**Issue by lasota** [transformstudios/statamic-events#63]
I seem to be getting an incomplete paginate array.  I have 23 events I'm trying to  paginate through and when I try to use the pagination in either the `events:in` or the `events:between` versions.
 
```
{{ events:in collection="events" next="1 year" paginate="9" }}
    {{ paginate | dump }}
{{ /events:in }}
```

The call above is producing the dump below when I'm on the /events?page=2 route.

<img width="552" alt="Screenshot 2023-09-21 at 11 13 29 PM" src="https://github.com/transformstudios/statamic-events/assets/5107146/2c95c07d-2d09-4d9c-960b-64c1a6bdbecd">

I'm currently on Statatmic version 4.21 and Events 5.0.1

**Comment by edalzell** [comment]
I get a 404 on the /events page: 
<img width="1332" alt="CleanShot 2023-09-22 at 10 59 36@2x" src="https://github.com/transformstudios/statamic-events/assets/6069653/e0f4c3a9-4bb4-40a3-8edb-2cab303e642a">

**Comment by edalzell** [comment]
Looks like 2 issues:

1. the prev/next links are wrong (missing `events`)
2. on the other pages it's showing data from the first page

**Comment by edalzell** [comment]
@lasota please update and try again

**Comment by lasota** [comment]
Works great, thank you!
