### ISSUE TITLE
Timezone field addition causes Call to a member function field() on null

### ISSUE THREAD

**Issue by sheldonkotyk** [transformstudios/statamic-events#69]
Updating from 5.0.2 to 5.0.4 on a multisite install. 

I get the following stacktrace.

![CleanShot 2023-10-10 at 21 54 07@2x](https://github.com/transformstudios/statamic-events/assets/622598/e73484d8-e195-4c67-83f5-3648caef9314)

I can't save any entries in any collections, regardless of whether they have the event fieldset. Opening the events collection which has the fieldset won't even list entries.

Reverting to 5.0.2 fixes the site. Updating to 5.0.3 shows the issue. updating to 5.0.4 doesn't fix it for me.

I also get the issue where I cannot publish the event fieldset. (I already had it but even deleting it didn't solve it.)

INFO  No publishable resources for tag [events-fieldsets].

**Comment by edalzell** [comment]
Sorry about that @sheldonkotyk, we’ll get an update out this week that addresses this.

**Comment by edalzell** [comment]
> I also get the issue where I cannot publish the event fieldset. (I already had it but even deleting it didn't solve it.)

You don't need to publish the fieldset anymore, you can just import `events:event` if you wanna use it.
