### ISSUE TITLE
Ability to set exclusions for recurring events

### ISSUE THREAD

**Issue by duncanmcclean** [transformstudios/statamic-events#78]
I'm considering using this addon as part of a site we're looking to move over from Craft CMS & the Calendar plugin over there.

We use the "recurring events" feature pretty heavily. We have lots of events that run every week, every month, etc.

One of the things we sometimes need to do is exclude a "recurring date", for example during the holidays, so the event runs every week, apart from one week where it doesn't. 

I imagine this could be achieved in the Control Panel with a Grid of date fields. Then, before returning a recurring event in the Antlers Tags, you check if it's included in the "excluded dates" field and if it is, prevent it being returned.

**Comment by edalzell** [comment]
I’ve been waiting for this request

**Comment by duncanmcclean** [comment]
And now you have a reason to build it. Have fun! 😅

**Comment by edalzell** [comment]
> And now you have a reason to build it. Have fun! 😅

will get to this in the next few weeks

**Comment by duncanmcclean** [comment]
No worries! I have no rush.
