### ISSUE TITLE
Addon settings for v3

### ISSUE THREAD

**Issue by 1stevengrant** [transformstudios/statamic-events#8]
Hey folks,
A couple of questions now that I'm integrating this into our project this week.

The docs make mention of addon settings but not sure where these would exist in v3.

Wondering also, if that's what's causing the illegal offset type in this snippet

```
{{ events:upcoming collection="stevens_events" limit="2" }}
{{ dates }}
...other entry data
{{ date }} <br>
{{ /dates }}
{{ /events:upcoming }}
```

**Comment by edalzell** [comment]
and which 'offset' is off? `period`? `recurrence`?

**Comment by edalzell** [comment]
Sorry @1stevengrant is this still an issue? Just saw this was on the old v2 version, so it slipped by me, sorry.

**Comment by 1stevengrant** [comment]
I believe so, yeah. Haven't checked for a couple of weeks though.

New Statamic version could have resolved the issue?

**Comment by edalzell** [comment]
> I believe so, yeah. Haven't checked for a couple of weeks though. New Statamic version could have resolved the issue?

what versions of Events and Statamic?

**Comment by edalzell** [comment]
Can't reproduce, please re-open if this is still occurring.
