### ISSUE TITLE
Clarify docs regarding setting collection in add-on settings

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-events#9]
Trying to use the Statamic EVENTS template.

https://statamic.com/addons/transform/events

In the docs, it says: "In the addon settings, pick the collection that has your Events."

The docs don't describe where these addon settings are. Can you elaborate? (And maybe update the docs as to what file we need to edit?)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3mb67)

**Comment by adnankussair** [comment]
Let's add clarity by specifying the exact location of the addon settings where we set the collection, basically `site/settings/events.yaml`

**Comment by edalzell** [comment]
Done
