### ISSUE TITLE
Status Filter

### ISSUE THREAD

**Issue by panda4man** [transformstudios/statamic-events#96]
Addon Version: 5.4.3
Statamic Version: 5.39.0

I just recently updated my Statamic v4 to v5 and now all my events have disappeared on the front end of the site. I believe it is due to a change in query behavior for the `status` field.

This line inside the Events class seems to be causing issues with how Statamic filters entries based on the `status` field.

https://github.com/transformstudios/statamic-events/blob/main/src/Events.php#L153

Statamic\Eloquent\Entries\EntryQueryBuilder (via \Statamic\Stache\Query\QueriesEntryStatus) leverages the new `whereStatus` method to directly filter the `status` field on a given entry.

I think we just need to change #L153 to be `whereStatus('published')` to get things working. At least that did the trick on my local instance.

**Comment by edalzell** [comment]
We use this all the time on our sites with no issues, what template code are you using where they disappeared?

**Comment by panda4man** [comment]
Hmm, curious. Perhaps there's something I'm doing incorrectly with how I'm querying the events then. It's just very strange that this broke during the move over to v5.

Here's the line that's broken right now:

```
Generator::fromCollection('events_simpleview')
                        ->sort('asc')
                        ->filter('id:in', $ids->join('|'))
                        ->collapseMultiDays()
                        ->upcoming(10);
```

This returns 0 results unless I make the core code change to `whereStatus` that I mentioned in the OP.

For some background, this is inside a custom tag. This tag aggregates data from various sources depending on the parameter passed into it which is why we are directly calling some of the underlying Event classes instead of using Event tags. Further, we are leveraging the eloquent-driver for this site, so the events are being stored in the database.

**Comment by panda4man** [comment]
I've done some more digging, and here is some more background. I think this may be stemming from our use of the eloquent-driver package. 

When the private [`entries()`](https://github.com/transformstudios/statamic-events/blob/main/src/Events.php#L145) method is called, specifically [line 153](https://github.com/transformstudios/statamic-events/blob/main/src/Events.php#L153), this calls the underlying EloquentQueryBuilder [`where()`](https://github.com/statamic/cms/blob/5.x/src/Query/EloquentQueryBuilder.php#L122) method. The column name it passes into the `$this->builder->where()` call is `data->status`, which makes sense when using the eloquent-driver package as everything is dumped into the `data` json column (unless you are using the column mapping setting). The issue is that there is no `status` field in the JSON blob. There is a `published` column which properly reflects the published/unpublished status of each event in the CP.

Perhaps there was parity between how eloquent-driver and stache handled the `status`/`published` in Statamic v4, but I think something changed in v5. I don't even see the `QueriesEntryStatus` trait that v5 uses to handle the dynamic nature of `status` and `published` in v4.

I think the path forward may be to move over to the new way that the Statamic [docs](https://statamic.dev/upgrade-guide/4-to-5#entries-may-now-only-be-queried-by-a-single-status) outline for status querying, but if I am totally missing something and there's a better way forward, I'm all ears.

**Comment by edalzell** [comment]
Great find @panda4man, thanks!

**Comment by panda4man** [comment]
@edalzell Would it be helpful if I created a PR for this fix or is something you want to tackle?

**Comment by edalzell** [comment]
> @edalzell Would it be helpful if I created a PR for this fix or is something you want to tackle?

A PR would be amazing thanks. I had/have planned to do this in the next couple of weeks.
